[sdl]
output=texture

[render]
aspect=off
glshader=none

[cpu]
cycles=max
cpu_cycles=max
cpu_cycles_protected=auto

[mouse]
mouse_capture = seamless
mouse_middle_release = false
builtin_dos_mouse_driver_model = wheel